"""Copy for the search landing pages. Rendered by gen.py (seo_page).

One page per thing a studio actually types into a search bar. Each page has to stand
on its own: unique copy, real credits only, no invented numbers or turnaround promises.
"""

PAGES = [
    {
        "slug": "rigging-outsourcing",
        "nav": "Rigging outsourcing",
        "title": "Rigging Outsourcing Studio for Animation, VFX &amp; Games | Bluetape",
        "desc": "Outsource character, creature and facial rigging to a specialist studio. Maya and Unreal Engine, your naming conventions, your rig system or ours.",
        "kicker": "Rigging outsourcing",
        "h1": "Rigging outsourcing for studios that ship.",
        "lead": "A specialist rigging studio you can hand a full character package to, or plug into a running show as extra capacity. Maya and Unreal Engine, built to your conventions.",
        "img": "hero-rig.webp",
        "deliver": [
            "Animation-ready character, creature and prop rigs",
            "Facial systems, correctives and skinning",
            "Game-ready skeletons built to a joint budget",
            "Rigs that follow your naming, folder structure and publish process",
            "Rig documentation and a walkthrough on handover",
            "Fixes and revisions through the agreed rounds",
        ],
        "body": [
            ("Outsourcing without the clean-up afterwards", "The risk with outsourced rigging is getting back rigs that work but don’t belong in your pipeline: wrong names, wrong hierarchy, controls your animators have to relearn. We start from your conventions, so the rigs we deliver look like the ones your own team builds."),
            ("Whatever system you rig with", "We work inside your in-house autorig, mGear or another framework, build by hand when that’s the better call, or use our own tools when the choice is ours. The system is your decision; the deliverable is the same."),
            ("Scoped before anyone opens Maya", "You send the asset list, the target engine or renderer, the deadline and an example of your conventions. We come back with what we’d do first, the risks we see, and whether the date is realistic, including telling you when we’re not the right studio for it."),
        ],
        "fit": [
            "Your rigging department is full and the asset list keeps growing",
            "You need a full character package delivered, not just extra hands",
            "Creatures or game rigs are outside your team’s usual work",
            "You want rigs that arrive inside your pipeline, not beside it",
        ],
        "work": ["speedrunners-2", "nicktoons-dice", "pudgy-party", "schweppes"],
        "faq": [
            ("How does rigging outsourcing work with Bluetape?", "You send the asset list, engine or renderer, deadline and your conventions. We agree scope, deliverables and revision rounds in writing, deliver rough rigs early so animation can start, then refine and hand over with documentation."),
            ("Can you work under NDA?", "Yes, as standard. Most of our work sits behind another studio’s name."),
            ("Do you work remotely?", "Yes. We work remotely with studios worldwide across animation, VFX and games."),
        ],
    },
    {
        "slug": "creature-rigging",
        "nav": "Creature &amp; animal rigging",
        "title": "Creature &amp; Animal Rigging Services — Quadrupeds &amp; Wings | Bluetape",
        "desc": "Creature and animal rigging for animation, VFX and games: quadrupeds, wings and birds, tails, and layered chains that hold up at extreme range.",
        "kicker": "Creature rigging",
        "h1": "Creature and animal rigging.",
        "lead": "Quadrupeds, wings, birds, tails and spines that refuse to behave. The characters where off-the-shelf autorigs give up are the ones we like most.",
        "img": None,
        "icon": "block-13",
        "deliver": [
            "Quadruped legs rigged from the animal’s real skeleton",
            "Wing systems: a primary chain to pose, feather groups that follow",
            "Per-feather offsets to break the fan by hand where a shot needs it",
            "Tails, necks and spines with blendable FK and spline layers",
            "Simulation layered on top where the pipeline supports it",
            "Deformation tested at the extremes, not just the bind pose",
        ],
        "body": [
            ("An animal is not a rotated human", "A dog’s hind leg bends the other way from a person’s knee because the joint that looks like a knee is an ankle. Rigging it as a rotated human leg makes every walk cycle a fight. We rig from the real anatomy, so the controls match how the animal actually moves."),
            ("Wings animators can pose", "A wing with dozens of feathers needs a structure that poses as one shape, then lets an animator break individual feathers where a shot calls for it. We build the fan as a driven system with manual offsets on top."),
            ("Chains that hit the frame", "Tails and necks get both an authored FK layer and a smooth spline layer, blendable. Simulation can sit on top, but never instead of animation control, because a creature still has to hit a specific silhouette on a specific frame."),
        ],
        "fit": [
            "Your autorig handles bipeds but not quadrupeds or wings",
            "A creature’s deformation fails at extreme poses",
            "You need birds, reptiles or fantasy anatomy that mixes both",
            "Game creatures that must stay inside a joint budget",
        ],
        "work": ["pudgy-party"],
        "faq": [
            ("Do you rig quadrupeds for games as well as film?", "Yes. For games we agree the joint budget per region up front and validate the export skeleton; for animation and VFX the budget is set by deformation quality instead."),
            ("Can you rig wings and birds?", "Yes. Wing systems with a posable primary chain, feather groups that follow it and per-feather offsets are a core part of our creature work."),
            ("Can you add simulation to a creature rig?", "Yes, where your pipeline supports it. Simulation is layered on top of the animation controls, never a replacement for them."),
        ],
    },
    {
        "slug": "game-character-rigging",
        "nav": "Game character rigging",
        "title": "Game Character Rigging for Unreal Engine &amp; Unity | Bluetape",
        "desc": "Game-ready character rigging built to a joint budget, with clean exports and validated skeletons for Unreal Engine and Unity.",
        "kicker": "Game rigging",
        "h1": "Game-ready character rigging.",
        "lead": "Rigs built to a joint budget agreed up front, exported clean and checked before they reach your engine, so problems show up in Maya and not during integration.",
        "img": "game-rig.webp",
        "deliver": [
            "Joint budget agreed and split by body region before rigging starts",
            "Clean, engine-ready export skeletons",
            "Validation of joint count, orientation, bind pose and naming",
            "Morph target naming that matches your engine setup",
            "Control Rig and Blueprint integration in Unreal where needed",
            "Animation rigs in Maya that drive the export skeleton",
        ],
        "body": [
            ("The export is a contract", "Every game rig has two audiences: the animators in Maya and the engine at runtime. We treat the export skeleton as a contract with its own acceptance test — count, orientation, bind pose, naming, morph target names — so nothing surprises you during integration."),
            ("Budgets up front, not discovered late", "Joint counts are agreed and split by region before a joint is placed: how many for the face, the hands, the cloth, the extras. That keeps the rig cheap without losing the deformation where the camera actually looks."),
            ("Shipped on real games", "We’ve rigged for SpeedRunners 2: King of Speed, Nicktoons &amp; The Dice of Destiny and Pudgy Party, for studios including Fair Play Labs."),
        ],
        "fit": [
            "You need characters rigged to a strict joint or bone budget",
            "Exports keep breaking between Maya and the engine",
            "You want Control Rig set up alongside the Maya rig",
            "Your team needs extra rigging capacity during production",
        ],
        "work": ["speedrunners-2", "nicktoons-dice", "pudgy-party"],
        "faq": [
            ("Do you rig for Unity as well as Unreal Engine?", "Yes. The export skeleton is built for your target engine, and the checks we run before delivery follow that engine’s requirements."),
            ("Can you keep a character under a joint budget?", "Yes. The budget is agreed and split by region before rigging starts, and every delivery is checked against it."),
            ("Can you work with our existing game skeleton?", "Yes. We can rig to a skeleton you already ship with, so animations stay compatible across characters."),
        ],
    },
    {
        "slug": "facial-rigging",
        "nav": "Facial rigging",
        "title": "Facial Rigging Services for Animation, VFX &amp; Games | Bluetape",
        "desc": "Facial rigging for characters in animation, VFX and games: joint and blendshape faces, correctives, eyes, lips and controls animators like to use.",
        "kicker": "Facial rigging",
        "h1": "Facial rigging animators want to use.",
        "lead": "Faces carry the performance. We build facial systems with controls laid out around how your animators work, and deformation that holds up close to camera.",
        "img": "hero-rig.webp",
        "deliver": [
            "Joint-based, blendshape or hybrid facial rigs",
            "Jaw, lips, eyelids, brows, cheeks and eyes",
            "Correctives for the shapes a face really makes",
            "On-face and panel controls, to your animators’ preference",
            "Game faces built inside an agreed joint budget",
            "Morph targets named for your engine",
        ],
        "body": [
            ("Controls first", "A facial rig lives or dies by how quickly an animator can hit an expression. We agree the control layout with your team before building, and keep it consistent across every character on the show."),
            ("Joints, shapes or both", "Film faces often lean on blendshapes and correctives; game faces usually have to work in joints and a small number of morph targets. We pick the approach from the target, not habit, and can match the system your studio already uses."),
            ("Held up at the extremes", "Sticky lips, eyelids closing over the eye, cheeks that raise under a smile. We test the faces in the expressions the show needs, not just the neutral pose."),
        ],
        "fit": [
            "Your characters need facial performance, not just a jaw open",
            "Game faces have to fit a strict joint budget",
            "You want faces that match an existing house style of controls",
            "An existing face rig doesn’t deform well close to camera",
        ],
        "work": [],
        "faq": [
            ("Do you build blendshape or joint-based facial rigs?", "Both, and hybrids. The choice depends on your target — film, series or game engine — and on what your pipeline already supports."),
            ("Can you match our existing facial control layout?", "Yes. Matching a studio’s established layout is often the fastest route for animators."),
            ("Do you do facial rigs for games?", "Yes, built inside an agreed joint budget with morph targets named for your engine."),
        ],
    },
    {
        "slug": "mgear-rigging",
        "nav": "mGear rigging",
        "title": "mGear Rigging Services &amp; Production Support | Bluetape",
        "desc": "mGear rigging services: character setup, custom components, guide templates and production support for studios that rig in mGear.",
        "kicker": "mGear rigging",
        "h1": "mGear rigging and production support.",
        "lead": "If your studio rigs in mGear, we rig in mGear. Character setup, custom work on top of your guides, and extra capacity on a show that is already running.",
        "img": "nicktoons-dice.webp",
        "deliver": [
            "Character setup from your mGear guides and templates",
            "Custom steps and post-build scripts for your pipeline",
            "Facial and correctives on top of the mGear build",
            "Fixes and updates to rigs already in production",
            "Rigs that rebuild cleanly from guides, the way mGear intends",
            "Documentation for anything custom we add",
        ],
        "body": [
            ("Your system, not ours", "We have our own rigging framework, but when a show is built in mGear the right answer is mGear. Rigs that match the rest of the production are worth more than rigs built our way."),
            ("Rebuildable, not patched", "mGear’s strength is rebuilding the rig from guides. Custom work goes into build steps and scripts rather than hand edits on the output, so a guide change doesn’t throw away days of fixes."),
            ("Production support", "On Nicktoons &amp; The Dice of Destiny we provided mGear rigging and production support for Fair Play Labs, working alongside the existing team."),
        ],
        "fit": [
            "Your pipeline is built on mGear and you need more riggers",
            "You need custom components or build steps added",
            "Rigs in production need fixes without breaking the rebuild",
            "You’re moving to mGear and want help with templates",
        ],
        "work": ["nicktoons-dice"],
        "faq": [
            ("Do you only work with mGear?", "No. We rig in mGear, other frameworks and in-house autorigs, by hand, or with our own tools. For mGear productions, we stay in mGear."),
            ("Can you add custom steps to our mGear build?", "Yes. Custom work goes into build steps and scripts so rigs still rebuild cleanly from guides."),
            ("Have you shipped mGear rigs in production?", "Yes, including rigging and production support on Nicktoons &amp; The Dice of Destiny for Fair Play Labs."),
        ],
    },
    {
        "slug": "unreal-engine-rigging",
        "nav": "Unreal Engine rigging",
        "title": "Unreal Engine Rigging — Control Rig &amp; Blueprints | Bluetape",
        "desc": "Unreal Engine rigging: Control Rig setup, clean skeleton exports from Maya, Blueprint integration and engine-side rig checks.",
        "kicker": "Unreal Engine",
        "h1": "Unreal Engine rigging and Control Rig.",
        "lead": "Characters that go from Maya into Unreal without surprises, with Control Rig and Blueprint integration where your project needs to animate or adjust in engine.",
        "img": "game-rig.webp",
        "deliver": [
            "Clean skeleton exports from Maya into Unreal",
            "Control Rig setups for in-engine animation and adjustment",
            "Blueprint integration for rig-driven behaviour",
            "Morph targets and correctives set up for the engine",
            "Checks on the exported skeleton before delivery",
            "Rigs that fit an existing project skeleton",
        ],
        "body": [
            ("Two rigs, one character", "Most game characters have an animation rig in Maya and a runtime skeleton in Unreal. We build both so they agree: the animation rig drives an export skeleton that is checked before it ever reaches the engine."),
            ("Control Rig where it earns it", "Control Rig is useful for in-engine animation, procedural adjustments and fixes after import. We add it where the project actually needs it rather than duplicating the Maya rig for its own sake."),
            ("Found in Maya, not in the engine", "Joint count, orientation, bind pose, naming and morph target names are all validated before delivery. Problems that would otherwise surface during integration get fixed in Maya first."),
        ],
        "fit": [
            "Imports into Unreal keep breaking or drifting",
            "You want animators to work in engine with Control Rig",
            "Characters need to share an existing project skeleton",
            "Correctives and morph targets need to survive the export",
        ],
        "work": [],
        "faq": [
            ("Do you set up Control Rig in Unreal Engine?", "Yes, for in-engine animation, procedural adjustments and post-import fixes, where the project needs it."),
            ("Can you rig to our existing Unreal skeleton?", "Yes. Rigging to a shared project skeleton keeps animation compatible across characters."),
            ("Do you also build the Maya animation rig?", "Yes. Usually the Maya rig drives the export skeleton, and both are delivered together."),
        ],
    },
    {
        "slug": "custom-autorig-development",
        "nav": "Custom autorig development",
        "title": "Custom Autorig &amp; Rigging Pipeline Development | Bluetape",
        "desc": "We design and build custom autorigs, rigging frameworks and Python tools for studios, or adapt the system you already use. Maya, Python, PySide.",
        "kicker": "Rigging systems",
        "h1": "Custom autorigs and rigging pipelines.",
        "lead": "When no existing system fits your shows, we build one that does: an autorig, a set of rigging tools, or adapters that make your current system work better. Documented, and yours.",
        "img": "code.webp",
        "deliver": [
            "Autorigs and modular rigging frameworks for Maya",
            "Adapters and extensions for the system you already use",
            "Pickers, animation tools and rig utilities",
            "Publish checks and validators for rigs and exports",
            "Save and load for guides, skin weights and rig parts",
            "Code written to your standards, with documentation",
        ],
        "body": [
            ("Built around your shows", "A rigging system should encode how your studio rigs: its naming, its control shapes, its engine targets. We start from the characters you actually make and design the system around them."),
            ("Extend before you replace", "Often the best move is not a new autorig but better tools around the one you have. We’ll tell you which is cheaper for your situation."),
            ("Yours when we leave", "Everything is written to your coding standards, in Python and PySide/Qt, and documented so your team owns it after the contract. We also maintain our own open-source framework, Mutant Tools, so we know what it takes to keep a rigging system alive."),
        ],
        "fit": [
            "Your riggers repeat the same setup work on every character",
            "Your current autorig can’t handle creatures or game rigs",
            "You need publish checks so broken rigs stop reaching animation",
            "You want a rigging system your own team can extend",
        ],
        "work": [],
        "faq": [
            ("Can you build an autorig for our studio?", "Yes. We design and build autorigs and modular rigging frameworks for Maya around your characters, naming and engine targets."),
            ("Can you improve our existing rigging tools instead?", "Yes, and it’s often cheaper. We extend and adapt existing systems as well as building new ones."),
            ("Who owns the code?", "You do, written to your standards and documented for your team."),
        ],
    },
    {
        "slug": "rig-troubleshooting",
        "nav": "Rig rescue &amp; troubleshooting",
        "title": "Rig Rescue &amp; Rig Troubleshooting for Productions | Bluetape",
        "desc": "Rig troubleshooting for running productions: broken deformation, failed exports and rigs left behind by someone who’s gone. Diagnosed, fixed and documented.",
        "kicker": "Rig rescue",
        "h1": "Rig rescue for running productions.",
        "lead": "Deformation failed review, the export broke, or the person who built the rig has left. We find what’s actually wrong and fix it without restarting the asset, unless restarting is genuinely cheaper.",
        "img": None,
        "icon": "block-08",
        "deliver": [
            "Diagnosis of what’s actually breaking, not just the symptom",
            "Deformation and skinning repairs",
            "Export and engine import fixes",
            "Stabilising rigs already in animation without breaking shots",
            "A written account of what was wrong and what changed",
            "Handover notes so your team can maintain it",
        ],
        "body": [
            ("Diagnostic first", "The first pass is finding the cause, not polishing the surface. A deformation problem might be skinning, a bad corrective or a hierarchy issue; an export failure might be one joint’s orientation. We fix the cause so it stays fixed."),
            ("Without breaking animation", "Rigs mid-production already have shots animated on them. We change what needs changing while keeping existing animation working, and tell you up front if something can’t be kept."),
            ("Any system, any author", "Rigs built in-house, in mGear, in another framework or by hand. Picking up someone else’s rig is a normal job for us."),
        ],
        "fit": [
            "A rig failed review and the deadline hasn’t moved",
            "Exports to the engine have started failing",
            "The rig’s author has left and nobody knows how it works",
            "Deformation breaks in poses the show now needs",
        ],
        "work": [],
        "faq": [
            ("Can you fix a rig somebody else built?", "Yes. That’s the normal case for rig rescue, whatever system it was built in."),
            ("Will fixing the rig break existing animation?", "We work to keep existing animation working, and tell you up front if a fix can’t preserve it."),
            ("Do we get documentation of the fix?", "Yes: a written account of what was wrong, what changed, and how to maintain it."),
        ],
    },
]
